# Generated by Django 6.0.2 on 2026-02-08 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='winner_role',
            field=models.CharField(blank=True, choices=[('villain', 'Méchant'), ('kind', 'Gentil')], max_length=20, null=True),
        ),
    ]
