# Generated by Django 6.0.2 on 2026-02-09 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_game_winner_role'),
        ('game', '0002_remove_winner'),
    ]

    operations = [
    ]
