# Generated by Django 6.0.2 on 2026-02-12 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_merge_0002_game_winner_role_0002_remove_winner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participation',
            name='info',
            field=models.CharField(choices=[('pire', 'Pire joueur'), ('neutre', 'Neutre'), ('meilleur', 'Meilleur joueur')], default='neutre', max_length=20),
        ),
    ]
