# Generated by Django 6.1.1 on 2026-10-06 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_alter_participation_info'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='game',
            options={'ordering': ['-started_at', '-id'], 'verbose_name': 'partie'},
        ),
        migrations.AlterModelOptions(
            name='participation',
            options={'ordering': ['player__name']},
        ),
        migrations.AlterModelOptions(
            name='player',
            options={'ordering': ['name'], 'verbose_name': 'joueur'},
        ),
        migrations.AlterUniqueTogether(
            name='participation',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='game',
            name='ended_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='fin'),
        ),
        migrations.AlterField(
            model_name='game',
            name='master',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mastered_games', to='game.player', verbose_name='maître du jeu'),
        ),
        migrations.AlterField(
            model_name='game',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='début'),
        ),
        migrations.AlterField(
            model_name='game',
            name='winner_role',
            field=models.CharField(blank=True, choices=[('kind', 'Gentil'), ('villain', 'Méchant')], max_length=20, null=True, verbose_name='camp gagnant'),
        ),
        migrations.AlterField(
            model_name='participation',
            name='info',
            field=models.CharField(choices=[('pire', 'Pire joueur'), ('neutre', 'Neutre'), ('meilleur', 'Meilleur joueur')], default='neutre', max_length=20, verbose_name='distinction'),
        ),
        migrations.AlterField(
            model_name='participation',
            name='role',
            field=models.CharField(choices=[('kind', 'Gentil'), ('villain', 'Méchant')], default='kind', max_length=20, verbose_name='rôle'),
        ),
        migrations.AlterField(
            model_name='player',
            name='name',
            field=models.CharField(max_length=150, unique=True, verbose_name='nom'),
        ),
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['started_at'], name='game_started_idx'),
        ),
        migrations.AddConstraint(
            model_name='participation',
            constraint=models.UniqueConstraint(fields=('player', 'game'), name='unique_player_per_game'),
        ),
    ]
